name: Generate Model Card

on:
  pull_request:
    paths:
      - 'docs/setup/**'
      - 'src/models/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  modelcard_generator:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12.7'

        - name: Install dependencies
          run: |
            pip install mlflow==2.16.2
            pip install jinja2
            sudo apt-get update
            sudo apt-get install -y jq

        - name: Create Model Cards
          run: |
            OUTPUT=$(python docs/src/main.py)

            if [ -n "$OUTPUT" ]; then
                COMMENT=$(echo "$OUTPUT" | jq -Rs .)
                PR_NUMBER=${{ github.event.pull_request.number }}
                PR_NUMBER=${{ github.event.pull_request.number }}
                curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
                -d "{\"body\":$COMMENT}"
            fi

        - name: Commit and push Model Cards
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add docs/modelcards/
            git commit -m "Model Cards generated" || echo "Nothing to commit"
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}